channels:
  - conda-forge
  - anaconda

dependencies:
  - showyourwork==0.4.2
  - conda-forge::numpy=1.26.4
  - conda-forge::pip=24.0
  - conda-forge::python=3.10.14
  - pip:
      - matplotlib==3.8.4
